In [2]:
import pandas as pd

In [14]:
file_string = "Resources/education.csv"

edf2 = pd.read_csv(file_string)

In [15]:
edf2

,FIPS Code,State,Area name,2003 Rural-urban Continuum Code,2003 Urban Influence Code,2013 Rural-urban Continuum Code,2013 Urban Influence Code,City/Suburb/Town/Rural 2013,"Less than a high school diploma, 1970","High school diploma only, 1970",...,"Percent of adults completing some college or associate's degree, 2000","Percent of adults with a bachelor's degree or higher, 2000","Less than a high school diploma, 2015-19","High school diploma only, 2015-19","Some college or associate's degree, 2015-19","Bachelor's degree or higher, 2015-19","Percent of adults with less than a high school diploma, 2015-19","Percent of adults with a high school diploma only, 2015-19","Percent of adults completing some college or associate's degree, 2015-19","Percent of adults with a bachelor's degree or higher, 2015-19"
0,1007,AL,Bibb County,1.0,1.0,1.0,1.0,City,"5,272","1,402",...,20.4,7.1,"3,386","7,256","3,848","1,678",20.9,44.9,23.8,10.4
1,1009,AL,Blount County,1.0,1.0,1.0,1.0,City,"10,677","3,440",...,24.8,9.6,"7,763","13,299","13,519","5,210",19.5,33.4,34.0,13.1
2,1021,AL,Chilton County,1.0,1.0,1.0,1.0,City,"10,285","2,805",...,20.5,9.9,"5,474","13,348","7,401","3,823",18.2,44.4,24.6,12.7
3,1073,AL,Jefferson County,1.0,1.0,1.0,1.0,City,"186,882","101,656",...,28.4,24.6,"44,684","118,636","136,299","150,124",9.9,26.4,30.3,33.4
4,1115,AL,St. Clair County,1.0,1.0,1.0,1.0,City,"10,304","3,540",...,25.6,11.1,"9,488","21,849","20,207","9,880",15.4,35.6,32.9,16.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3278,53000,WA,Washington,NaN,NaN,NaN,NaN,NaN,"666,656","661,800",...,34.4,27.7,"442,449","1,122,330","1,699,233","1,837,612",8.7,22.0,33.3,36.0
3279,54000,WV,West Virginia,NaN,NaN,NaN,NaN,NaN,"566,026","267,165",...,21.0,14.8,"168,624","519,091","334,314","265,398",13.1,40.3,26.0,20.6
3280,55000,WI,Wisconsin,NaN,NaN,NaN,NaN,NaN,"1,060,531","811,048",...,28.1,22.4,"308,216","1,211,981","1,244,179","1,191,329",7.8,30.6,31.5,30.1
3281,56000,WY,Wyoming,NaN,NaN,NaN,NaN,NaN,"65,252","63,630",...,35.0,21.9,"26,688","113,535","143,438","106,855",6.8,29.1,36.7,27.4
3282,72000,PR,Puerto Rico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.4,18.3,"550,182","655,680","533,214","606,883",23.5,27.9,22.7,25.9

In [17]:
edf_filter = edf2[['FIPS Code', 'State',
                    'Percent of adults with less than a high school diploma, 2015-19', 
                   'Percent of adults with a high school diploma only, 2015-19',
                   "Percent of adults completing some college or associate's degree, 2015-19",
                  "Percent of adults with a bachelor's degree or higher, 2015-19"]].copy()
edf_filter

,FIPS Code,State,"Percent of adults with less than a high school diploma, 2015-19","Percent of adults with a high school diploma only, 2015-19","Percent of adults completing some college or associate's degree, 2015-19","Percent of adults with a bachelor's degree or higher, 2015-19"
0,1007,AL,20.9,44.9,23.8,10.4
1,1009,AL,19.5,33.4,34.0,13.1
2,1021,AL,18.2,44.4,24.6,12.7
3,1073,AL,9.9,26.4,30.3,33.4
4,1115,AL,15.4,35.6,32.9,16.1
...,...,...,...,...,...,...
3278,53000,WA,8.7,22.0,33.3,36.0
3279,54000,WV,13.1,40.3,26.0,20.6
3280,55000,WI,7.8,30.6,31.5,30.1
3281,56000,WY,6.8,29.1,36.7,27.4
3282,72000,PR,23.5,27.9,22.7,25.9

In [ ]:
edf_filter.csv('Resources/education_cl')