In [1]:
import pandas as pd
from sqlalchemy import create_engine
import os

In [6]:
unemployment_file = "resources/unemployment2019.csv"
unemployment_df = pd.read_csv(unemployment_file)
unemployment_df.head()

,FIPS_Code,State,Area_name,Rural_urban_continuum_code_2013,Urban_influence_code_2013,City/Suburb/Town/Rural,Metro_2013,Civilian_labor_force_2019,Employed_2019,Unemployed_2019,Unemployment_rate_2019,Median_Household_Income_2019,Med_HH_Income_Percent_of_State_Total_2019
0,1007,AL,"Bibb County, AL",1.0,1.0,City,1.0,"8,639","8,371",268,3.1,"47,918",92.6
1,1009,AL,"Blount County, AL",1.0,1.0,City,1.0,"25,196","24,516",680,2.7,"52,902",102.2
2,1021,AL,"Chilton County, AL",1.0,1.0,City,1.0,"19,841","19,296",545,2.7,"49,692",96.0
3,1073,AL,"Jefferson County, AL",1.0,1.0,City,1.0,"316,802","307,648","9,154",2.9,"54,127",104.6
4,1115,AL,"St. Clair County, AL",1.0,1.0,City,1.0,"40,698","39,591","1,107",2.7,"65,403",126.3

In [12]:
unemployment_clean_df=unemployment_df.drop(['Rural_urban_continuum_code_2013', 'Urban_influence_code_2013', 'City/Suburb/Town/Rural', 'Metro_2013', 'Civilian_labor_force_2019', 'Employed_2019', 'Median_Household_Income_2019', 'Med_HH_Income_Percent_of_State_Total_2019' ], axis=1)

In [13]:
unemployment_clean_df.head()

,FIPS_Code,State,Area_name,Unemployed_2019,Unemployment_rate_2019
0,1007,AL,"Bibb County, AL",268,3.1
1,1009,AL,"Blount County, AL",680,2.7
2,1021,AL,"Chilton County, AL",545,2.7
3,1073,AL,"Jefferson County, AL","9,154",2.9
4,1115,AL,"St. Clair County, AL","1,107",2.7

In [15]:
unemployment_clean_df.rename(columns={'FIPS_Code': 'FIPS Code', 'Area_name': 'Area Name', 'Unemployed_2019': 'Unemployed 2019', 'Unemployment_rate_2019':'Unemployment Rate 2019'}, inplace=True)
unemployment_clean_df.head()

,FIPS Code,State,Area Name,Unemployed 2019,Unemployment Rate 2019
0,1007,AL,"Bibb County, AL",268,3.1
1,1009,AL,"Blount County, AL",680,2.7
2,1021,AL,"Chilton County, AL",545,2.7
3,1073,AL,"Jefferson County, AL","9,154",2.9
4,1115,AL,"St. Clair County, AL","1,107",2.7